// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Project struct {
	_tab flatbuffers.Table
}

func GetRootAsProject(buf []byte, offset flatbuffers.UOffsetT) *Project {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Project{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsProject(buf []byte, offset flatbuffers.UOffsetT) *Project {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Project{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Project) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Project) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Project) Repo() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Project) Mark() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Project) MutateMark(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func ProjectStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ProjectAddRepo(builder *flatbuffers.Builder, repo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(repo), 0)
}
func ProjectAddMark(builder *flatbuffers.Builder, mark byte) {
	builder.PrependByteSlot(1, mark, 0)
}
func ProjectEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
