// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: struct.proto

package protobuf.kogan;

public final class Struct {
  private Struct() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.kogan.Project)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string repo = 1;</code>
     * @return The repo.
     */
    java.lang.String getRepo();
    /**
     * <code>string repo = 1;</code>
     * @return The bytes for repo.
     */
    com.google.protobuf.ByteString
        getRepoBytes();

    /**
     * <code>bytes mark = 2;</code>
     * @return The mark.
     */
    com.google.protobuf.ByteString getMark();
  }
  /**
   * Protobuf type {@code protobuf.kogan.Project}
   */
  public static final class Project extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.kogan.Project)
      ProjectOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Project.newBuilder() to construct.
    private Project(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Project() {
      repo_ = "";
      mark_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Project();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.kogan.Struct.internal_static_protobuf_kogan_Project_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.kogan.Struct.internal_static_protobuf_kogan_Project_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.kogan.Struct.Project.class, protobuf.kogan.Struct.Project.Builder.class);
    }

    public static final int REPO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object repo_ = "";
    /**
     * <code>string repo = 1;</code>
     * @return The repo.
     */
    @java.lang.Override
    public java.lang.String getRepo() {
      java.lang.Object ref = repo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        repo_ = s;
        return s;
      }
    }
    /**
     * <code>string repo = 1;</code>
     * @return The bytes for repo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRepoBytes() {
      java.lang.Object ref = repo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        repo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARK_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString mark_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes mark = 2;</code>
     * @return The mark.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMark() {
      return mark_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(repo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, repo_);
      }
      if (!mark_.isEmpty()) {
        output.writeBytes(2, mark_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(repo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, repo_);
      }
      if (!mark_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, mark_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.kogan.Struct.Project)) {
        return super.equals(obj);
      }
      protobuf.kogan.Struct.Project other = (protobuf.kogan.Struct.Project) obj;

      if (!getRepo()
          .equals(other.getRepo())) return false;
      if (!getMark()
          .equals(other.getMark())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPO_FIELD_NUMBER;
      hash = (53 * hash) + getRepo().hashCode();
      hash = (37 * hash) + MARK_FIELD_NUMBER;
      hash = (53 * hash) + getMark().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.kogan.Struct.Project parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Project parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Project parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Project parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Project parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Project parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.kogan.Struct.Project prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.kogan.Project}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.kogan.Project)
        protobuf.kogan.Struct.ProjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Project_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Project_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.kogan.Struct.Project.class, protobuf.kogan.Struct.Project.Builder.class);
      }

      // Construct using protobuf.kogan.Struct.Project.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        repo_ = "";
        mark_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Project_descriptor;
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Project getDefaultInstanceForType() {
        return protobuf.kogan.Struct.Project.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Project build() {
        protobuf.kogan.Struct.Project result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Project buildPartial() {
        protobuf.kogan.Struct.Project result = new protobuf.kogan.Struct.Project(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protobuf.kogan.Struct.Project result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.repo_ = repo_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mark_ = mark_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.kogan.Struct.Project) {
          return mergeFrom((protobuf.kogan.Struct.Project)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.kogan.Struct.Project other) {
        if (other == protobuf.kogan.Struct.Project.getDefaultInstance()) return this;
        if (!other.getRepo().isEmpty()) {
          repo_ = other.repo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getMark() != com.google.protobuf.ByteString.EMPTY) {
          setMark(other.getMark());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                repo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                mark_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object repo_ = "";
      /**
       * <code>string repo = 1;</code>
       * @return The repo.
       */
      public java.lang.String getRepo() {
        java.lang.Object ref = repo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          repo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string repo = 1;</code>
       * @return The bytes for repo.
       */
      public com.google.protobuf.ByteString
          getRepoBytes() {
        java.lang.Object ref = repo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          repo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string repo = 1;</code>
       * @param value The repo to set.
       * @return This builder for chaining.
       */
      public Builder setRepo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        repo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string repo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRepo() {
        repo_ = getDefaultInstance().getRepo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string repo = 1;</code>
       * @param value The bytes for repo to set.
       * @return This builder for chaining.
       */
      public Builder setRepoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        repo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mark_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes mark = 2;</code>
       * @return The mark.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMark() {
        return mark_;
      }
      /**
       * <code>bytes mark = 2;</code>
       * @param value The mark to set.
       * @return This builder for chaining.
       */
      public Builder setMark(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        mark_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes mark = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMark() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mark_ = getDefaultInstance().getMark();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.kogan.Project)
    }

    // @@protoc_insertion_point(class_scope:protobuf.kogan.Project)
    private static final protobuf.kogan.Struct.Project DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.kogan.Struct.Project();
    }

    public static protobuf.kogan.Struct.Project getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Project>
        PARSER = new com.google.protobuf.AbstractParser<Project>() {
      @java.lang.Override
      public Project parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Project> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Project> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.kogan.Struct.Project getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.kogan.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string login = 2;</code>
     * @return The login.
     */
    java.lang.String getLogin();
    /**
     * <code>string login = 2;</code>
     * @return The bytes for login.
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>string group = 3;</code>
     * @return The group.
     */
    java.lang.String getGroup();
    /**
     * <code>string group = 3;</code>
     * @return The bytes for group.
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <code>bytes practice = 4;</code>
     * @return The practice.
     */
    com.google.protobuf.ByteString getPractice();

    /**
     * <code>.protobuf.kogan.Project project = 5;</code>
     * @return Whether the project field is set.
     */
    boolean hasProject();
    /**
     * <code>.protobuf.kogan.Project project = 5;</code>
     * @return The project.
     */
    protobuf.kogan.Struct.Project getProject();
    /**
     * <code>.protobuf.kogan.Project project = 5;</code>
     */
    protobuf.kogan.Struct.ProjectOrBuilder getProjectOrBuilder();

    /**
     * <code>float mark = 6;</code>
     * @return The mark.
     */
    float getMark();
  }
  /**
   * Protobuf type {@code protobuf.kogan.Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.kogan.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      login_ = "";
      group_ = "";
      practice_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.kogan.Struct.internal_static_protobuf_kogan_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.kogan.Struct.internal_static_protobuf_kogan_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.kogan.Struct.Student.class, protobuf.kogan.Struct.Student.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object login_ = "";
    /**
     * <code>string login = 2;</code>
     * @return The login.
     */
    @java.lang.Override
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      }
    }
    /**
     * <code>string login = 2;</code>
     * @return The bytes for login.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object group_ = "";
    /**
     * <code>string group = 3;</code>
     * @return The group.
     */
    @java.lang.Override
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <code>string group = 3;</code>
     * @return The bytes for group.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRACTICE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString practice_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes practice = 4;</code>
     * @return The practice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPractice() {
      return practice_;
    }

    public static final int PROJECT_FIELD_NUMBER = 5;
    private protobuf.kogan.Struct.Project project_;
    /**
     * <code>.protobuf.kogan.Project project = 5;</code>
     * @return Whether the project field is set.
     */
    @java.lang.Override
    public boolean hasProject() {
      return project_ != null;
    }
    /**
     * <code>.protobuf.kogan.Project project = 5;</code>
     * @return The project.
     */
    @java.lang.Override
    public protobuf.kogan.Struct.Project getProject() {
      return project_ == null ? protobuf.kogan.Struct.Project.getDefaultInstance() : project_;
    }
    /**
     * <code>.protobuf.kogan.Project project = 5;</code>
     */
    @java.lang.Override
    public protobuf.kogan.Struct.ProjectOrBuilder getProjectOrBuilder() {
      return project_ == null ? protobuf.kogan.Struct.Project.getDefaultInstance() : project_;
    }

    public static final int MARK_FIELD_NUMBER = 6;
    private float mark_ = 0F;
    /**
     * <code>float mark = 6;</code>
     * @return The mark.
     */
    @java.lang.Override
    public float getMark() {
      return mark_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(login_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, login_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, group_);
      }
      if (!practice_.isEmpty()) {
        output.writeBytes(4, practice_);
      }
      if (project_ != null) {
        output.writeMessage(5, getProject());
      }
      if (java.lang.Float.floatToRawIntBits(mark_) != 0) {
        output.writeFloat(6, mark_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(login_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, login_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(group_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, group_);
      }
      if (!practice_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, practice_);
      }
      if (project_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getProject());
      }
      if (java.lang.Float.floatToRawIntBits(mark_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, mark_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.kogan.Struct.Student)) {
        return super.equals(obj);
      }
      protobuf.kogan.Struct.Student other = (protobuf.kogan.Struct.Student) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getLogin()
          .equals(other.getLogin())) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getPractice()
          .equals(other.getPractice())) return false;
      if (hasProject() != other.hasProject()) return false;
      if (hasProject()) {
        if (!getProject()
            .equals(other.getProject())) return false;
      }
      if (java.lang.Float.floatToIntBits(getMark())
          != java.lang.Float.floatToIntBits(
              other.getMark())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + PRACTICE_FIELD_NUMBER;
      hash = (53 * hash) + getPractice().hashCode();
      if (hasProject()) {
        hash = (37 * hash) + PROJECT_FIELD_NUMBER;
        hash = (53 * hash) + getProject().hashCode();
      }
      hash = (37 * hash) + MARK_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMark());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.kogan.Struct.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.kogan.Struct.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.kogan.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.kogan.Student)
        protobuf.kogan.Struct.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.kogan.Struct.Student.class, protobuf.kogan.Struct.Student.Builder.class);
      }

      // Construct using protobuf.kogan.Struct.Student.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        login_ = "";
        group_ = "";
        practice_ = com.google.protobuf.ByteString.EMPTY;
        project_ = null;
        if (projectBuilder_ != null) {
          projectBuilder_.dispose();
          projectBuilder_ = null;
        }
        mark_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Student_descriptor;
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Student getDefaultInstanceForType() {
        return protobuf.kogan.Struct.Student.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Student build() {
        protobuf.kogan.Struct.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Student buildPartial() {
        protobuf.kogan.Struct.Student result = new protobuf.kogan.Struct.Student(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(protobuf.kogan.Struct.Student result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.login_ = login_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.group_ = group_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.practice_ = practice_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.project_ = projectBuilder_ == null
              ? project_
              : projectBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.mark_ = mark_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.kogan.Struct.Student) {
          return mergeFrom((protobuf.kogan.Struct.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.kogan.Struct.Student other) {
        if (other == protobuf.kogan.Struct.Student.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLogin().isEmpty()) {
          login_ = other.login_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getPractice() != com.google.protobuf.ByteString.EMPTY) {
          setPractice(other.getPractice());
        }
        if (other.hasProject()) {
          mergeProject(other.getProject());
        }
        if (other.getMark() != 0F) {
          setMark(other.getMark());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                login_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                group_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                practice_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getProjectFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 53: {
                mark_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object login_ = "";
      /**
       * <code>string login = 2;</code>
       * @return The login.
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login = 2;</code>
       * @return The bytes for login.
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 2;</code>
       * @param value The login to set.
       * @return This builder for chaining.
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        login_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogin() {
        login_ = getDefaultInstance().getLogin();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string login = 2;</code>
       * @param value The bytes for login to set.
       * @return This builder for chaining.
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        login_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <code>string group = 3;</code>
       * @return The group.
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group = 3;</code>
       * @return The bytes for group.
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group = 3;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        group_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string group = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        group_ = getDefaultInstance().getGroup();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string group = 3;</code>
       * @param value The bytes for group to set.
       * @return This builder for chaining.
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        group_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString practice_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes practice = 4;</code>
       * @return The practice.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPractice() {
        return practice_;
      }
      /**
       * <code>bytes practice = 4;</code>
       * @param value The practice to set.
       * @return This builder for chaining.
       */
      public Builder setPractice(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        practice_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes practice = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPractice() {
        bitField0_ = (bitField0_ & ~0x00000008);
        practice_ = getDefaultInstance().getPractice();
        onChanged();
        return this;
      }

      private protobuf.kogan.Struct.Project project_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.kogan.Struct.Project, protobuf.kogan.Struct.Project.Builder, protobuf.kogan.Struct.ProjectOrBuilder> projectBuilder_;
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       * @return Whether the project field is set.
       */
      public boolean hasProject() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       * @return The project.
       */
      public protobuf.kogan.Struct.Project getProject() {
        if (projectBuilder_ == null) {
          return project_ == null ? protobuf.kogan.Struct.Project.getDefaultInstance() : project_;
        } else {
          return projectBuilder_.getMessage();
        }
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      public Builder setProject(protobuf.kogan.Struct.Project value) {
        if (projectBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          project_ = value;
        } else {
          projectBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      public Builder setProject(
          protobuf.kogan.Struct.Project.Builder builderForValue) {
        if (projectBuilder_ == null) {
          project_ = builderForValue.build();
        } else {
          projectBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      public Builder mergeProject(protobuf.kogan.Struct.Project value) {
        if (projectBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            project_ != null &&
            project_ != protobuf.kogan.Struct.Project.getDefaultInstance()) {
            getProjectBuilder().mergeFrom(value);
          } else {
            project_ = value;
          }
        } else {
          projectBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      public Builder clearProject() {
        bitField0_ = (bitField0_ & ~0x00000010);
        project_ = null;
        if (projectBuilder_ != null) {
          projectBuilder_.dispose();
          projectBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      public protobuf.kogan.Struct.Project.Builder getProjectBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getProjectFieldBuilder().getBuilder();
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      public protobuf.kogan.Struct.ProjectOrBuilder getProjectOrBuilder() {
        if (projectBuilder_ != null) {
          return projectBuilder_.getMessageOrBuilder();
        } else {
          return project_ == null ?
              protobuf.kogan.Struct.Project.getDefaultInstance() : project_;
        }
      }
      /**
       * <code>.protobuf.kogan.Project project = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.kogan.Struct.Project, protobuf.kogan.Struct.Project.Builder, protobuf.kogan.Struct.ProjectOrBuilder> 
          getProjectFieldBuilder() {
        if (projectBuilder_ == null) {
          projectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.kogan.Struct.Project, protobuf.kogan.Struct.Project.Builder, protobuf.kogan.Struct.ProjectOrBuilder>(
                  getProject(),
                  getParentForChildren(),
                  isClean());
          project_ = null;
        }
        return projectBuilder_;
      }

      private float mark_ ;
      /**
       * <code>float mark = 6;</code>
       * @return The mark.
       */
      @java.lang.Override
      public float getMark() {
        return mark_;
      }
      /**
       * <code>float mark = 6;</code>
       * @param value The mark to set.
       * @return This builder for chaining.
       */
      public Builder setMark(float value) {
        
        mark_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>float mark = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMark() {
        bitField0_ = (bitField0_ & ~0x00000020);
        mark_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.kogan.Student)
    }

    // @@protoc_insertion_point(class_scope:protobuf.kogan.Student)
    private static final protobuf.kogan.Struct.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.kogan.Struct.Student();
    }

    public static protobuf.kogan.Struct.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.kogan.Struct.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.kogan.Students)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    java.util.List<protobuf.kogan.Struct.Student> 
        getStudentsList();
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    protobuf.kogan.Struct.Student getStudents(int index);
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    int getStudentsCount();
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    java.util.List<? extends protobuf.kogan.Struct.StudentOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    protobuf.kogan.Struct.StudentOrBuilder getStudentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.kogan.Students}
   */
  public static final class Students extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.kogan.Students)
      StudentsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Students.newBuilder() to construct.
    private Students(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Students() {
      students_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Students();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.kogan.Struct.internal_static_protobuf_kogan_Students_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.kogan.Struct.internal_static_protobuf_kogan_Students_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.kogan.Struct.Students.class, protobuf.kogan.Struct.Students.Builder.class);
    }

    public static final int STUDENTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<protobuf.kogan.Struct.Student> students_;
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    @java.lang.Override
    public java.util.List<protobuf.kogan.Struct.Student> getStudentsList() {
      return students_;
    }
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends protobuf.kogan.Struct.StudentOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    @java.lang.Override
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    @java.lang.Override
    public protobuf.kogan.Struct.Student getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <code>repeated .protobuf.kogan.Student students = 1;</code>
     */
    @java.lang.Override
    public protobuf.kogan.Struct.StudentOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(1, students_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, students_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.kogan.Struct.Students)) {
        return super.equals(obj);
      }
      protobuf.kogan.Struct.Students other = (protobuf.kogan.Struct.Students) obj;

      if (!getStudentsList()
          .equals(other.getStudentsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStudentsCount() > 0) {
        hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
        hash = (53 * hash) + getStudentsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.kogan.Struct.Students parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Students parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Students parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Students parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Students parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.kogan.Struct.Students parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.kogan.Struct.Students prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.kogan.Students}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.kogan.Students)
        protobuf.kogan.Struct.StudentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Students_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Students_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.kogan.Struct.Students.class, protobuf.kogan.Struct.Students.Builder.class);
      }

      // Construct using protobuf.kogan.Struct.Students.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
        } else {
          students_ = null;
          studentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.kogan.Struct.internal_static_protobuf_kogan_Students_descriptor;
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Students getDefaultInstanceForType() {
        return protobuf.kogan.Struct.Students.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Students build() {
        protobuf.kogan.Struct.Students result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.kogan.Struct.Students buildPartial() {
        protobuf.kogan.Struct.Students result = new protobuf.kogan.Struct.Students(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(protobuf.kogan.Struct.Students result) {
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
      }

      private void buildPartial0(protobuf.kogan.Struct.Students result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.kogan.Struct.Students) {
          return mergeFrom((protobuf.kogan.Struct.Students)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.kogan.Struct.Students other) {
        if (other == protobuf.kogan.Struct.Students.getDefaultInstance()) return this;
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                protobuf.kogan.Struct.Student m =
                    input.readMessage(
                        protobuf.kogan.Struct.Student.parser(),
                        extensionRegistry);
                if (studentsBuilder_ == null) {
                  ensureStudentsIsMutable();
                  students_.add(m);
                } else {
                  studentsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<protobuf.kogan.Struct.Student> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          students_ = new java.util.ArrayList<protobuf.kogan.Struct.Student>(students_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.kogan.Struct.Student, protobuf.kogan.Struct.Student.Builder, protobuf.kogan.Struct.StudentOrBuilder> studentsBuilder_;

      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public java.util.List<protobuf.kogan.Struct.Student> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public protobuf.kogan.Struct.Student getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder setStudents(
          int index, protobuf.kogan.Struct.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder setStudents(
          int index, protobuf.kogan.Struct.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder addStudents(protobuf.kogan.Struct.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder addStudents(
          int index, protobuf.kogan.Struct.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder addStudents(
          protobuf.kogan.Struct.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder addStudents(
          int index, protobuf.kogan.Struct.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends protobuf.kogan.Struct.Student> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public protobuf.kogan.Struct.Student.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public protobuf.kogan.Struct.StudentOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public java.util.List<? extends protobuf.kogan.Struct.StudentOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public protobuf.kogan.Struct.Student.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            protobuf.kogan.Struct.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public protobuf.kogan.Struct.Student.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, protobuf.kogan.Struct.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.kogan.Student students = 1;</code>
       */
      public java.util.List<protobuf.kogan.Struct.Student.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.kogan.Struct.Student, protobuf.kogan.Struct.Student.Builder, protobuf.kogan.Struct.StudentOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protobuf.kogan.Struct.Student, protobuf.kogan.Struct.Student.Builder, protobuf.kogan.Struct.StudentOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.kogan.Students)
    }

    // @@protoc_insertion_point(class_scope:protobuf.kogan.Students)
    private static final protobuf.kogan.Struct.Students DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.kogan.Struct.Students();
    }

    public static protobuf.kogan.Struct.Students getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Students>
        PARSER = new com.google.protobuf.AbstractParser<Students>() {
      @java.lang.Override
      public Students parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Students> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Students> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.kogan.Struct.Students getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_kogan_Project_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_kogan_Project_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_kogan_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_kogan_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_kogan_Students_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_kogan_Students_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014struct.proto\022\016protobuf.kogan\"%\n\007Projec" +
      "t\022\014\n\004repo\030\001 \001(\t\022\014\n\004mark\030\002 \001(\014\"\177\n\007Student" +
      "\022\014\n\004name\030\001 \001(\t\022\r\n\005login\030\002 \001(\t\022\r\n\005group\030\003" +
      " \001(\t\022\020\n\010practice\030\004 \001(\014\022(\n\007project\030\005 \001(\0132" +
      "\027.protobuf.kogan.Project\022\014\n\004mark\030\006 \001(\002\"5" +
      "\n\010Students\022)\n\010students\030\001 \003(\0132\027.protobuf." +
      "kogan.Studentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_kogan_Project_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_kogan_Project_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_kogan_Project_descriptor,
        new java.lang.String[] { "Repo", "Mark", });
    internal_static_protobuf_kogan_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_kogan_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_kogan_Student_descriptor,
        new java.lang.String[] { "Name", "Login", "Group", "Practice", "Project", "Mark", });
    internal_static_protobuf_kogan_Students_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protobuf_kogan_Students_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_kogan_Students_descriptor,
        new java.lang.String[] { "Students", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
