#!/bin/bash

rm -rf .rdx/brix
mkdir .rdx/brix

echo "{@alice-2 1:2, 3:4}" >1.jdr
echo "{@bob-4 5:6, 7:8}" >2.jdr
echo "{@abc-1 3:3}" >3.jdr

./rdx parse 1.jdr, write 1.rdx
./rdx parse 2.jdr, write 2.rdx
./rdx parse 3.jdr, write 3.rdx

./brix patch 1.rdx
./brix patch 2.rdx
./brix patch 3.rdx

rm 1.jdr 1.rdx 2.jdr 2.rdx 3.jdr 3.rdx
