// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: struct.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package protobuf.kogan;

@kotlin.jvm.JvmName("-initializestudent")
public inline fun student(block: protobuf.kogan.StudentKt.Dsl.() -> kotlin.Unit): protobuf.kogan.Struct.Student =
  protobuf.kogan.StudentKt.Dsl._create(protobuf.kogan.Struct.Student.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `protobuf.kogan.Student`
 */
public object StudentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: protobuf.kogan.Struct.Student.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: protobuf.kogan.Struct.Student.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): protobuf.kogan.Struct.Student = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string login = 2;`
     */
    public var login: kotlin.String
      @JvmName("getLogin")
      get() = _builder.getLogin()
      @JvmName("setLogin")
      set(value) {
        _builder.setLogin(value)
      }
    /**
     * `string login = 2;`
     */
    public fun clearLogin() {
      _builder.clearLogin()
    }

    /**
     * `string group = 3;`
     */
    public var group: kotlin.String
      @JvmName("getGroup")
      get() = _builder.getGroup()
      @JvmName("setGroup")
      set(value) {
        _builder.setGroup(value)
      }
    /**
     * `string group = 3;`
     */
    public fun clearGroup() {
      _builder.clearGroup()
    }

    /**
     * `bytes practice = 4;`
     */
    public var practice: com.google.protobuf.ByteString
      @JvmName("getPractice")
      get() = _builder.getPractice()
      @JvmName("setPractice")
      set(value) {
        _builder.setPractice(value)
      }
    /**
     * `bytes practice = 4;`
     */
    public fun clearPractice() {
      _builder.clearPractice()
    }

    /**
     * `.protobuf.kogan.Project project = 5;`
     */
    public var project: protobuf.kogan.Struct.Project
      @JvmName("getProject")
      get() = _builder.getProject()
      @JvmName("setProject")
      set(value) {
        _builder.setProject(value)
      }
    /**
     * `.protobuf.kogan.Project project = 5;`
     */
    public fun clearProject() {
      _builder.clearProject()
    }
    /**
     * `.protobuf.kogan.Project project = 5;`
     * @return Whether the project field is set.
     */
    public fun hasProject(): kotlin.Boolean {
      return _builder.hasProject()
    }

    /**
     * `float mark = 6;`
     */
    public var mark: kotlin.Float
      @JvmName("getMark")
      get() = _builder.getMark()
      @JvmName("setMark")
      set(value) {
        _builder.setMark(value)
      }
    /**
     * `float mark = 6;`
     */
    public fun clearMark() {
      _builder.clearMark()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun protobuf.kogan.Struct.Student.copy(block: `protobuf.kogan`.StudentKt.Dsl.() -> kotlin.Unit): protobuf.kogan.Struct.Student =
  `protobuf.kogan`.StudentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val protobuf.kogan.Struct.StudentOrBuilder.projectOrNull: protobuf.kogan.Struct.Project?
  get() = if (hasProject()) getProject() else null

