[0].name: Ivan Alexandrovich Ivanov
[0].login: ivanovia
[0].group: GUP-12
[0].practice.[0]: 1
[0].practice.[1]: 1
[0].practice.[2]: 0
[0].practice.[3]: 0
[0].practice.[4]: 0
[0].practice.[5]: 0
[0].practice.[6]: 0
[0].practice.[7]: 0
[0].project.repo: github.com/decentralized-hse/practice/tree/main/04-formats
[0].project.mark: 9
[0].mark: 8
[1].name: Petvor Peter
[1].login: petr
[1].group: GUP-11
[1].practice.[0]: 1
[1].practice.[1]: 1
[1].practice.[2]: 0
[1].practice.[3]: 1
[1].practice.[4]: 0
[1].practice.[5]: 0
[1].practice.[6]: 0
[1].practice.[7]: 1
[1].project.repo: github.com//practice/tree/main/04-formats
[1].project.mark: 7
[1].mark: 8.61
