#!/bin/python3

import os
import sys

import paramiko

VERBOSE = True

def get_remote_brik_files(ssh):
    command = "ls brix/.rdx/brix"
    try:
        _, stdout, stderr = ssh.exec_command(command)
        output = stdout.read().decode().strip()
        error = stderr.read().decode().strip()
        if VERBOSE and error:
            print(f"Command {command} got following errors: {error}")
        return output.split("\n")
    except Exception as e:
        print(f"Command failed with error: {e}")
        ssh.close()
        sys.exit(1)


def get_local_brik_files():
    files = os.listdir(".rdx/brix")
    return files


def run_sync(host, port, username, password):
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    try:
        ssh.connect(host, port, username, password)
    except Exception as e:
        print(f"Connection failed with error: {e}")
        sys.exit(1)
    
    remote_brik_files = get_remote_brik_files(ssh)
    local_brik_files = get_local_brik_files()
    print(remote_brik_files, local_brik_files)
    print("Syncing is over")
    ssh.close()


if __name__ == "__main__":
    host = "127.0.0.1"
    port = 2222
    username = "testuser"
    password = "testpass"
    
    run_sync(host, port, username, password)
