#!/bin/python3

import os
import subprocess
import sys

import paramiko

VERBOSE = True

def get_remote_brik_files_names(ssh):
    command = "ls .rdx/brix"
    try:
        _, stdout, stderr = ssh.exec_command(command)
        output = stdout.read().decode().strip()
        error = stderr.read().decode().strip()
        if VERBOSE and error:
            print(f"Command {command} got following errors: {error}")
        return output.split("\n")
    except Exception as e:
        print(f"Command failed with error: {e}")
        ssh.close()
        sys.exit(1)


def merge_remote_brik_files(ssh, brik_files):
    command = "./brix"
    for i, brik_file in enumerate(brik_files):
        command += f" add {brik_file[:10]}"
        if i + 1 < len(brik_file):
            command += ','
    command += " merge"

    try:
        _, stdout, stderr = ssh.exec_command(command)
        output = stdout.read().decode().strip()
        error = stderr.read().decode().strip()
        if VERBOSE and error:
            print(f"Command {command} got following errors: {error}")
        return output.strip()
    except Exception as e:
        print(f"Command failed with error: {e}")
        ssh.close()
        sys.exit(1)


def clear_remote_brik_files(ssh, brik_files):
    command = "rm"
    for brik_file in brik_files:
        command += f" .rdx/brix/{brik_file}"

    try:
        _, _, stderr = ssh.exec_command(command)
        error = stderr.read().decode().strip()
        if VERBOSE and error:
            print(f"Command {command} got following errors: {error}")
        return
    except Exception as e:
        print(f"Command failed with error: {e}")
        return


def fetch_remote_brik_file(ssh, brik_file_hash):
    try:
        sftp = ssh.open_sftp()
        filename = f".rdx/brix/{brik_file_hash}.brik"
        sftp.get(filename, filename)
    except Exception as e:
        print(f"Command failed with error: {e}")
        ssh.close()
        sys.exit(1)
    finally:
        sftp.close()


def merge_local_brik_files():
    files = os.listdir(".rdx/brix")

    if len(files) == 0:
        return

    command = ["./brix"]
    for file in files:
        command.append(f" add {file[:10]},")
    command.append("merge")
    
    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        check=True,
    )

    for file in files:
        os.remove(f".rdx/brix/{file}")

    return result.stdout.strip()


def send_brik_file_to_remote(ssh, brik_file_hash):
    try:
        sftp = ssh.open_sftp()
        filename = f".rdx/brix/{brik_file_hash}.brik"
        sftp.put(filename, filename)
    except Exception as e:
        print(f"Command failed with error: {e}")
        ssh.close()
        sys.exit(1)
    finally:
        sftp.close()


def run_sync(host, port, username, password):
    # TODO: add lock against data races
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    try:
        ssh.connect(host, port, username, password)
    except Exception as e:
        print(f"Connection failed with error: {e}")
        sys.exit(1)
    
    remote_brik_files_names = get_remote_brik_files_names(ssh)
    merged_file_hash = merge_remote_brik_files(ssh, remote_brik_files_names)
    clear_remote_brik_files(ssh, remote_brik_files_names)
    
    fetch_remote_brik_file(ssh, merged_file_hash)
    clear_remote_brik_files(ssh, [f'{merged_file_hash}.brik'])

    local_merged_file_hash = merge_local_brik_files()
    send_brik_file_to_remote(ssh, local_merged_file_hash)

    print("Syncing is over")
    ssh.close()


if __name__ == "__main__":
    host = "127.0.0.1"
    port = 2222
    username = "testuser"
    password = "testpass"
    
    run_sync(host, port, username, password)
