#!/bin/bash

rm -rf .rdx/brix
mkdir .rdx/brix

echo "{@kek-14 1:2, 3:4}" >1.jdr
echo "{@lol-411 5:6, 7:8}" >2.jdr

./rdx parse 1.jdr, write 1.rdx
./rdx parse 2.jdr, write 2.rdx

./brix patch 1.rdx
./brix patch 2.rdx

rm 1.jdr 1.rdx 2.jdr 2.rdx
